export default {
  'lib':'fw',
  'anim':'anim',
  'inverted':'inv',
  'active':'active',
  'selectable':'select',
  'title':'title',
  'name':'name',
  'list':'list',
  'block':'block',
  'image':'img',
  'circle':'c',
  'loading':'loading',
  'shadow':'sh-',
  'shadowHover':'shh-',
  'simpleHover':'simpleh',
  'iconInside':'i',
  'shadowActive':'sha',
  'disabled':'disabled',
  'contour':'contour',
  'center':'ctr',
  'left':'lft',
  'right':'rgt',
  'simple':'simple',
  'icon':'if',
  'vertical':'vrt',
  'incard':'incard',
  'input':'input',
  'size':'s-',
  'relativeSize':'r-',
  'stroke':'stroke',
  'content':'content',
  'meta':'meta',
  'basic':' brd b-t',
  'compact':' compact',
  'horizontalStretch':'h-stretch',
  'verticalStretch':'v-stretch',

  'min':'min',
  'alt':'alt-',
  'part':'part',
  'transparent':'alpha',
  'headSection':'head section',
  'section':'section',
  'header':'header',
  'question':'ref',
  'svg':'svg',
  'small':'small',
  'valid':'val',
  'error':'err',
  'inputs':'fw sin',
  'label':'label',
  'semi':'semi',
  'light':'light'
}
